data_root: "DATA"
val_root: "DATA"
batch_size: 4
beta1: 0.5
beta2: 0.999
lambda_l1: 100
lambda_tv: 3
lambda_lpips: 5
save_dir_gen: "MODELS/TRAINED_TOGETHER/GENERATORS/LEARNING_RATE_TUNING/RESNETSPADE_LPIPSTV_RGB_DARK_100"
save_dir_disc: "MODELS/TRAINED_TOGETHER/DISCRIMINATORS/LEARNING_RATE_TUNING/RESNETSPADE_LPIPSTV_RGB_DARK_100"
image_output_dir: "DATA/RGB_LEARNING_RATE_TUNING/RESNETSPADE_LPIPSTV_RGB_DARK_100"
csv_log_path: "DATA/LOGS/RESNETSPADE_LPIPSTV_RGB_DARK_100.csv"